return {
	"AstroNvim/astrocommunity",
	{ import = "astrocommunity.utility.noice-nvim" },
	{ import = "astrocommunity.motion.nvim-surround" },
	{ import = "astrocommunity.lsp.inc-rename-nvim" },
	{ import = "astrocommunity.completion.cmp-cmdline" },
	{ import = "astrocommunity.scrolling.vim-smoothie" },
	{ import = "astrocommunity.colorscheme.moonfly" },
	{ import = "astrocommunity.colorscheme.tokyonight-nvim" },
	{ import = "astrocommunity.media.cord-nvim" },
	{ import = "astrocommunity.recipes.neovide" },
	{ import = "astrocommunity.recipes.vscode-icons" },
	{ import = "astrocommunity.recipes.heirline-vscode-winbar" },
	{ import = "astrocommunity.recipes.heirline-nvchad-statusline" },
}
